juser0719/LTF2_BE

src/main/java/com/lguplus/LTF2_BE/core/domain/Color.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Order.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Phone.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneColor.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneDesImg.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneImg.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneInfo.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Plan.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PlanMediaService.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PublicSupport.java

- 어떤 점이 바뀐건지 짧게 설명 
- (UI 변경있다면) 스크린샷 첨부
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-34] entity init

---

src/main/java/com/lguplus/LTF2_BE/core/domain/Color.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Orders.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Phone.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneColor.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneDesImg.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneImg.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneInfo.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Plan.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PlanMediaService.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PublicSupport.java
src/main/resources/application.properties

- 어떤 점이 바뀐건지 짧게 설명 
- jpa mysql과 연결, 엔티티 테이블명 명시
- (UI 변경있다면) 스크린샷 첨부
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-23] jpa db mapping

---

src/main/java/com/lguplus/LTF2_BE/api/util/ManuFacturingCompanyConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/MediaServiceConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/OrderPlanConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/PlanTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/TelecomTechConverter.java
src/main/java/com/lguplus/LTF2_BE/core/domain/ManuFacturingCompany.java
src/main/java/com/lguplus/LTF2_BE/core/domain/MediaService.java
src/main/java/com/lguplus/LTF2_BE/core/domain/OrderPlan.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Orders.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Phone.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Plan.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PlanMediaService.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PlanType.java
src/main/java/com/lguplus/LTF2_BE/core/domain/TelecomTech.java

- Converter Util 추가 및 매핑
PR 타입 명시
- [x ] New feature or enhancement
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-50] Convert util 작성

---

src/main/java/com/lguplus/LTF2_BE/core/repository/ColorRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/OrdersRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneColorRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneDesImgRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneImgRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneInfoRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PlanMediaServiceRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PlanRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PublicSupportRepository.java
src/main/resources/application.properties

- jpa repository 파일 생성
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-34] repository init

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PhoneController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/ColorResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneInfoResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneRepository.java

- 상품 리스트 조회 API Controller, Service, Repository 작성
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-36] 상품 리스트 조회 API 1차 완성

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PlanController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/PlanResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/PlanService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PlanServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/api/util/ManuFacturingCompanyConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/MediaServiceConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/OrderPlanConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/PlanTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/TelecomTechConverter.java
src/main/java/com/lguplus/LTF2_BE/core/domain/ManuFacturingCompany.java
src/main/java/com/lguplus/LTF2_BE/core/domain/MediaService.java
src/main/java/com/lguplus/LTF2_BE/core/domain/OrderPlan.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PlanType.java
src/main/java/com/lguplus/LTF2_BE/core/domain/TelecomTech.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PlanRepository.java
src/main/resources/application.properties

- 요금제 조회 API 개발
- 각 Enum 클래스 별 convertvalue method 작성
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-37] 요금제 조회 API & convertValue Method

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PlanController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PlanResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/PlanService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PlanServiceImpl.java

- response의 telecomTech 값 수정
- resDto 내 생성자 Method 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-37] 요금제 조회수정

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PhoneController.java
src/main/java/com/lguplus/LTF2_BE/api/controller/PlanController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/ColorResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneDetailResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneColorRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneImgRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneRepository.java
src/main/resources/application.properties

- 상품 상세조회 API, 통신기술에 따른 상품 리스트 조회 API 작성
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-36] 상품 상세조회 API, 통신기술에 따른 상품 리스트 조회 API

---

.gitignore
src/main/java/com/lguplus/LTF2_BE/api/controller/PublicSupportController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PublicSupportPhoneResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PublicSupportPlanResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/PublicSupportService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PublicSupportServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PublicSupportRepository.java
src/main/resources/application.properties

- [LT2-55] public-support/plan/{plan_id}
- [LT2-56] public-support/phone/{phone_id}
- [LT2-57] public-support/phone/{phone_id}/plan/{plan_id}
PR 타입 명시

[LT2-54] 공시지원금 API

---

build.gradle
src/main/java/com/lguplus/LTF2_BE/api/config/SwaggerConfig.java
src/main/java/com/lguplus/LTF2_BE/api/controller/PhoneController.java
src/main/resources/application.properties

- swagger 설정 및 api 어노테이션 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-59] swagger config

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PlanController.java

- plan controller swagger 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-39] 요금제 컨트롤러 swagger

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PublicSupportController.java

[LT2-59] 공시지원금 swagger 적용

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PhoneController.java
src/main/java/com/lguplus/LTF2_BE/api/controller/PlanController.java
src/main/java/com/lguplus/LTF2_BE/api/controller/PublicSupportController.java
src/main/java/com/lguplus/LTF2_BE/api/controller/SearchController.java
src/main/resources/application.properties

- 별건 아니고 그냥 axios용 몇줄 추가했습니다~
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

CrossOrigin 어노테이션 추가

---

src/main/java/com/lguplus/LTF2_BE/api/controller/ShoppingBasketController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneInfoResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/ShoppingBasketResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/ShoppingBasketService.java
src/main/java/com/lguplus/LTF2_BE/api/service/ShoppingBasketServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneInfo.java

[LT2-62] 장바구니 api

---

src/main/java/com/lguplus/LTF2_BE/api/util/DeliveryTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/MediaServiceConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/PlanTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/core/domain/BillAcceptWay.java
src/main/java/com/lguplus/LTF2_BE/core/domain/CustomerType.java
src/main/java/com/lguplus/LTF2_BE/core/domain/DeliveryType.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Orders.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PayWay.java
src/main/resources/application.properties

- Order 관련 Entity 변경
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-38] Order Entity 변경

---

src/main/java/com/lguplus/LTF2_BE/api/util/BillAcceptWayConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/CustomerTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/PayWayConverter.java
src/main/java/com/lguplus/LTF2_BE/core/domain/BillAcceptWay.java
src/main/java/com/lguplus/LTF2_BE/core/domain/CustomerType.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Orders.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PayWay.java

- 추가 & 수정된 Entity의 Converter util 및 ConvertValue 메소드 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-50] 추가된 Entity Converter 작성

---

src/main/java/com/lguplus/LTF2_BE/Ltf2BeApplication.java
src/main/java/com/lguplus/LTF2_BE/api/controller/OrdersController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/request/OrdersReqDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/OrdersService.java
src/main/java/com/lguplus/LTF2_BE/api/service/OrdersServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Orders.java
src/main/resources/application.properties

- 상품 주문 API 관련 Controller, Service 작성
- JPA Auditing 기능 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-38] 상품 주문 API 작성

---

src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneResDto.java

- 핸드폰 조회 할때 주문수량이 필요해서 dto 수정하였습니다.
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-36] 주문수량 관련 dto fix

---

.github/workflows/build-gradle.yml

Java gradle build actions script 추가. main 또는 dev branch에 push event 발생 시 자동 테스트 후 빌드하는 동작을 수행.
만약에 forked repo에서 테스트나 빌드가 통과를 못한다면 수정을 다시 한 뒤에 Merge를 바랍니다.
PR 타입 명시

[LT2-52] add gradle build actions

---

src/test/java/com/lguplus/LTF2_BE/ShoppingBasketServiceTest.java

- ## Proposed changes
- 장바구니 테스트 케이스 작성
PR 타입 명시

[LT2-73] 장바구니 테스트 케이스 작성

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PhoneController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/request/OrdersReqDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneInfoResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/OrdersServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneInfo.java
src/test/java/com/lguplus/LTF2_BE/OrdersServiceTest.java
src/test/java/com/lguplus/LTF2_BE/PhoneServiceTest.java

- 주문, 상품 테스트 케이스 작성
- PhoneInfo의 storage column을 Integer로 변경
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-75] 주문, 상품 테스트 케이스 작성 및 PhoneInfo entity 변경

---

src/main/java/com/lguplus/LTF2_BE/api/config/SwaggerConfig.java
src/main/java/com/lguplus/LTF2_BE/api/controller/OrdersController.java
src/main/java/com/lguplus/LTF2_BE/api/controller/PhoneController.java
src/main/java/com/lguplus/LTF2_BE/api/service/OrdersService.java
src/main/java/com/lguplus/LTF2_BE/api/service/OrdersServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneColorRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneImgRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneRepository.java

- 상품, 주문 주석 작업
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-77] 상품, 주문 주석 작업

---

src/main/java/com/lguplus/LTF2_BE/aop/TimeTraceAop.java
src/main/java/com/lguplus/LTF2_BE/api/controller/PlanController.java
src/main/java/com/lguplus/LTF2_BE/api/controller/SearchController.java
src/main/java/com/lguplus/LTF2_BE/api/service/FixKeyWordServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/api/service/PlanServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/api/service/SearchServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/api/util/SymSpell.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/BillAcceptWayConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/CustomerTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/DeliveryTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/ManuFacturingCompanyConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/MediaServiceConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/PayWayConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/PlanTypeConverter.java
src/main/java/com/lguplus/LTF2_BE/api/util/converter/TelecomTechConverter.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PlanRepository.java

- Plan & Search & aop & util 주석 입니다
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-79] Plan & Search 기능 주석

---

src/main/java/com/lguplus/LTF2_BE/api/service/FixKeyWordServiceImpl.java
src/test/java/com/lguplus/LTF2_BE/FixKeyWordServiceTest.java
src/test/java/com/lguplus/LTF2_BE/PlanServiceTest.java
src/test/java/com/lguplus/LTF2_BE/SearchServiceTest.java

- 테스트 케이스 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-85] 테스트 케이스 추가

---

.github/workflows/build-gradle.yml
Dockerfile
build.gradle

build.gradle에 기본적으로 build하면 나오는 결과물을 app.jar로 고정.
RDS가 internet환경과 통신할 수 없기에 build clean test할 때 오류 발생하게 됨. 
따라서 build.gradle에서 build할 때 test는 진행하지 않도록 수정
PR 타입 명시

[LT2-52] add build actions script and add Dockerfile

---

src/main/java/com/lguplus/LTF2_BE/api/util/SymSpell.java

- 숫자 입력 시 제대로작동 안돼던 버그 수정
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-68] 맞춤법 검사 버그 수정

---

.github/workflows/deploy-dev.yml

- 백엔드 개발서버 배포 스크립트 작성
PR 타입 명시

[LT2-52] add backend dev server deployment script

---

src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/repository/OrdersRepository.java

- 주간판매량이 client에서 필요하여 추가하였습니다.
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

[LT2-36] 주간판매량 로직 추가

---

src/main/java/com/lguplus/LTF2_BE/api/controller/ShoppingBasketController.java
src/main/java/com/lguplus/LTF2_BE/api/service/ShoppingBasketService.java
src/main/java/com/lguplus/LTF2_BE/api/service/ShoppingBasketServiceImpl.java

[LT2-86] 장바구니 주석 처리

---

src/main/java/com/lguplus/LTF2_BE/api/controller/PublicSupportController.java
src/main/java/com/lguplus/LTF2_BE/api/service/PublicSupportService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PublicSupportServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PublicSupportRepository.java
src/test/java/com/lguplus/LTF2_BE/PublicSupportServiceTest.java

LT2-87 주석 추가 및 TC 작성

---

.github/workflows/build-gradle.yml
.github/workflows/deploy-dev.yml

- backend CI/CD script추가
PR 타입 명시

[LT-52] add backend deploy scripts

---

.github/workflows/deploy-dev.yml

[LT2-52] job 이름을 CI CD start로 수정

---

.github/workflows/deploy-dev.yml

- backend CI/CD 완성. fork에서 확인 완료
PR 타입 명시
- AWS credential에서 오류날 가능성 존재

[LT2-52] add backend deployment actions

---

src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneDetailResDto.java

- 상세페이지 Dto hotfix
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

Dto hotfix

---

.github/workflows/deploy-dev.yml

[LT2-52] for checking backend deploy

---

src/main/java/com/lguplus/LTF2_BE/api/config/SwaggerConfig.java
src/main/java/com/lguplus/LTF2_BE/api/controller/OrdersController.java
src/main/java/com/lguplus/LTF2_BE/api/controller/PhoneController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/request/OrdersReqDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/ColorResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneDetailResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneInfoResDto.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/PhoneResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/OrdersService.java
src/main/java/com/lguplus/LTF2_BE/api/service/OrdersServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneService.java
src/main/java/com/lguplus/LTF2_BE/api/service/PhoneServiceImpl.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Color.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Orders.java
src/main/java/com/lguplus/LTF2_BE/core/domain/Phone.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneColor.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneDesImg.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneImg.java
src/main/java/com/lguplus/LTF2_BE/core/domain/PhoneInfo.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneColorRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneImgRepository.java
src/main/java/com/lguplus/LTF2_BE/core/repository/PhoneRepository.java
src/test/java/com/lguplus/LTF2_BE/OrdersServiceTest.java
src/test/java/com/lguplus/LTF2_BE/PhoneServiceTest.java

- 작성한 부분 주석달았습니다.
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부

작성한 부분 주석달기

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

[LT2-52] backend ECS task definition수정에 따른 scripts변경

---

src/main/java/com/lguplus/LTF2_BE/api/controller/ShoppingBasketController.java
src/main/java/com/lguplus/LTF2_BE/api/dto/response/ShoppingBasketResDto.java
src/main/java/com/lguplus/LTF2_BE/api/service/ShoppingBasketService.java
src/main/java/com/lguplus/LTF2_BE/api/service/ShoppingBasketServiceImpl.java
src/test/java/com/lguplus/LTF2_BE/ShoppingBasketServiceTest.java

- ShoppingBasket 주석 작업
- (UI 변경있다면) 스크린샷 첨부
PR 타입 명시

ShoppingBasket 주석 작업
